name: Codecov
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  codecov:
    container:
      image: swift:5.4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --enable-code-coverage --filter '^((?!ipv6).)*$'
    - uses: mattpolzin/swift-codecov-action@0.6.1
