name: Codecov
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - run: uname -a
    - uses: fwal/setup-swift@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install curl -y
    - uses: actions/checkout@v2
    - run: swift test --enable-code-coverage --filter '^((?!ipv6).)*$'
    - run: ls **/*
    - run: llvm-cov report .build/x86_64-unknown-linux-gnu/debug/PredicatePackageTests.xctest -instr-profile=.build/x86_64-unknown-linux-gnu/debug/codecov/default.profdata -use-color
    - uses: codecov/codecov-action@v1
      with:
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
