name: Codecov
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install curl -y
    - uses: actions/checkout@v2
    - run: swift test --enable-code-coverage --filter '^((?!ipv6).)*$'
    - uses: codecov/codecov-action@v1
      with:
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
