name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    container:
      image: swift
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with Code Coverage
      run: swift test --enable-code-coverage --filter '^((?!ipv6).)*$'
    - name: Report Codecov
      run: | 
        llvm-cov report .build/debug/SwiftPublicIPPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata -use-color
    - name: Export Codecov
      run: |
        mkdir -p coverage
        llvm-cov export -format="lcov" .build/debug/SwiftPublicIPPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > ./coverage/lcov.info
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.run_id }}-codecov
        path: ./coverage/lcov.info
  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ github.run_id }}-codecov
        path: ./coverage/lcov.info
    - run: ls -R
    - uses: romeovs/lcov-reporter-action@v0.2.16
