name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    container:
      image: swift
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with Code Coverage
      run: swift test --enable-code-coverage --filter '^((?!ipv6).)*$'
    - name: Report Codecov
      run: | 
        llvm-cov report .build/debug/SwiftPublicIPPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata -use-color
    - name: Export Codecov
      run: |
        mkdir -p coverage
        llvm-cov export -format="lcov" .build/debug/SwiftPublicIPPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > ./coverage/lcov.info
    - name: Convert Absolute Path to Relative Path
      run: sed -i "s~/__w/Swift-Public-IP/Swift-Public-IP/~~g" ./coverage/lcov.info
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.run_id }}-codecov
        path: ./coverage/lcov.info
  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ github.run_id }}-codecov
        path: ./coverage/
    - run: ls -R
    - uses: HackingGate/lcov-reporter-action@7bf132b5f872f17fde607a37b7ca2308510abbb4
    - run: cat ./coverage/body.html
    - uses: actions/github-script@v4
      with:
        script: |
          fs = require('fs');
          fs.readFile('./coverage/body.html', 'utf8', function (error,data) {
            if (error) {
              console.log(error)
            }
            if (context.eventName === "pull_request") {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: data
              })
            } else if (context.eventName === "push") {
              github.issues.createCommitComment({
                commit_sha: options.commit,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: data
              })
            }
          });
