name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    container:
      image: swift
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with Code Coverage
      run: swift test --enable-code-coverage --filter '^((?!ipv6).)*$'
    - name: Report Codecov
      run: | 
        llvm-cov report .build/debug/SwiftPublicIPPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata -use-color
    - name: Export Codecov
      run: |
        mkdir -p coverage
        llvm-cov export -format="lcov" .build/debug/SwiftPublicIPPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > ./coverage/lcov.info
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.run_id }}-codecov
        path: ./coverage/lcov.info
  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ github.run_id }}-codecov
        path: ./coverage/
    - run: ls -R
    - uses: HackingGate/lcov-reporter-action@8e0e2f75214b17f82a09ba15ad79ab96b25c7cf4
    - name: Create Comment if Pull Request
      uses: actions/github-script@v4
      if: ${{ github.event_name === "pull_request" }}
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ./coverage/body.html
          })
    - name: Create Commit Comment if Push
      uses: actions/github-script@v4
      if: ${{ github.event_name === "push" }}
      with:
        script: |
          github.issues.createCommitComment({
            commit_sha: options.commit,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ./coverage/body.html
          })
