name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test with Code Coverage
      run: swift test --enable-code-coverage --filter '^((?!ipv6).)*$'
    - name: Link Codecov Report
      run: ln `swift test --show-codecov-path` Codecov-report.json
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./Codecov-report.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
